export type ThemeMode = "light" | "dark" | "system";

/** Tema efetivo aplicado na interface (após resolver "system"). */
export type ResolvedThemeMode = "light" | "dark";

export type ColorTokens = {
  bg: string;
  bgSoft: string;
  header: string;
  card: string;
  cardMuted: string;
  cardBorder: string;
  primary: string;
  primaryDark: string;
  primaryLight: string;
  primaryMuted: string;
  primaryText: string;
  text: string;
  textOnPrimary: string;
  muted: string;
  mutedOnPrimary: string;
  border: string;
  success: string;
  successBg: string;
  successDark: string;
  error: string;
  errorBg: string;
  errorDark: string;
  warning: string;
  warningBg: string;
  warningBorder: string;
  infoBg: string;
  infoBorder: string;
  infoText: string;
  streak: string;
  streakBg: string;
  metricBlueBg: string;
  metricBlueText: string;
  metricPurpleBg: string;
  metricGreenBg: string;
  navInactive: string;
  navBar: string;
  navBarBorder: string;
  navBarInactive: string;
  navBarActive: string;
  navBarActiveBg: string;
  overlayPurple: string;
  accentBlob: string;
  accentBlobSoft: string;
  lessonOpen: string;
  lessonDone: string;
  locked: string;
  shadow: string;
  heroBlob: string;
  heroBlobSmall: string;
  tabTrack: string;
  inputBg: string;
  bodyText: string;
};
